production:
  adapter: postgresql
  encoding: utf8
  database: hilander_production
  pool: 5
  host: localhost
  username: hilander
  password: asdasdas8duas8das8d

development:
  adapter: postgresql
  encoding: utf8
  database: highlander_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: highlander_test
  pool: 5
  host: localhost
